# Generated by Django 3.0.1 on 2020-02-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='des',
        ),
    ]
