# Generated by Django 3.0.1 on 2020-02-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0002_remove_course_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
