# Generated by Django 3.0.1 on 2020-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0003_auto_20200207_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='sq_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='topic_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
