# Generated by Django 3.0.1 on 2020-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0007_auto_20200307_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cimage',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
