# Generated by Django 3.0.1 on 2020-03-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0008_course_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='study_portal.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cimage',
            field=models.ImageField(default='', upload_to='study_portal/images'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_portal.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_portal.Course')),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_portal.Question')),
            ],
        ),
    ]
