# Generated by Django 3.0.1 on 2020-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0009_auto_20200309_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
