# Generated by Django 3.0.1 on 2020-03-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0012_auto_20200311_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_portal.Course'),
        ),
    ]
