# Generated by Django 3.0.1 on 2020-03-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0013_auto_20200311_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='que_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_portal.Question'),
        ),
    ]
