# Generated by Django 3.0.1 on 2020-03-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0014_auto_20200311_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_portal.Course'),
        ),
    ]
