# Generated by Django 3.0.1 on 2020-03-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0015_tutorial_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_portal.Course'),
        ),
    ]
