# Generated by Django 3.0.1 on 2020-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0016_video_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
