# Generated by Django 3.0.1 on 2020-04-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0018_auto_20200424_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a',
        ),
        migrations.AddField(
            model_name='answer',
            name='que_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_portal.Question'),
        ),
    ]
